### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by BerkanYildiz** [ClashofLights/Ultrapowa-Boom-Beach-Server#1]
I tht for a second you made a BB server, but i remembered your name is CoL, the king of bullshit and dmca.
So i looked a bit to the source code, and what i saw.. oh damn what i saw..

![image](https://cloud.githubusercontent.com/assets/15068742/25557450/ca0d8cf6-2d11-11e7-9093-7f2aded24372.png)

**Comment by ClashofLights** [comment]
Read the Readme ^^
